# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4363b108f20b6041f9b6a0c25c1c2898dee150a2ad10cf2c62cf19bbbf7be2a5362161e1feae75ca2ea6c8138c4f03d823dce8b2ffc14b2fd13b88bc1c11db0a

test:
  secret_key_base: 32a07dc718dedd30c6d8cc9d9c0ad0129aa750a7a3bff86fb02a436648cde809bd1039865db77002af3ea4eae47730981c674556cb5de0ee9b295512e5d78021

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
